http:
  middlewares:
    rl:
      rateLimit:
        average: 50
        burst: 100
    rl-prometheus:
      rateLimit:
        average: 50
        burst: 100
    auth-prometheus:
      basicAuth:
        users:
          - "pr-user:$2y$12$J887AlQOq3tPhiFC6g.RJu9cA4/PYES.J2A9O9gR2T8PyuWe/Q11e" # htpasswd -nBC 12 ""
    sec-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: same-origin
    ipallow:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32      # localhost
          - ::1/128           # ipv6 localhost

################# Trusted IPs #################
          - 24.135.81.177/32  # Stefan
          - 57.153.174.113/32 # - devops azure

################# AzureDevOps #################
################# AzureDevOps (BEGIN - auto) #################
          - 191.235.226.0/24
          - 20.125.155.0/24
          - 20.166.41.0/24
          - 20.189.107.0/24
          - 20.195.68.0/24
          - 20.204.197.192/26
          - 20.233.130.0/25
          - 20.37.158.0/23
          - 20.37.194.0/24
          - 20.39.13.0/26
          - 20.41.194.0/24
          - 20.41.6.0/23
          - 20.42.134.0/23
          - 20.42.226.0/24
          - 20.42.5.0/24
          - 20.45.196.64/26
          - 20.91.148.128/25
          - 40.119.10.0/24
          - 40.74.28.0/23
          - 40.80.187.0/24
          - 40.82.252.0/24
          - 51.104.26.0/24
          - 52.150.138.0/24
          - 52.228.82.0/24
################# AzureDevOps (END - auto) #################
