http:
  middlewares:
    rl:
      rateLimit:
        average: 50
        burst: 100
    rl-influxdb:
      rateLimit:
        average: 50
        burst: 100
    sec-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: same-origin
    ipallow:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32      # localhost
          - ::1/128           # ipv6 localhost
          - 24.135.88.181/32  # Stefan
